import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'
const schema=readFileSync('supabase/migrations/20260914100000_create_round_messages.sql','utf8')
const security=readFileSync('supabase/migrations/20260914101000_secure_round_messages.sql','utf8')
const publication=readFileSync('supabase/migrations/20260914102000_enable_round_messages_realtime.sql','utf8')
const code=security.replace(/--[^\n]*/g,'')
const reader=code.slice(0,code.indexOf('create function public.send_round_message'))
const sender=code.slice(code.indexOf('create function public.send_round_message'))

test('chat history FKs survive account/character deletion, protect rounds, and contain only Phase 3.1 fields',()=>{
  assert.match(schema,/round_id uuid not null references public.rounds\(id\) on delete restrict/)
  assert.match(schema,/author_user_id uuid references public.profiles\(id\) on delete set null/)
  assert.match(schema,/character_id uuid references public.characters\(id\) on delete set null/)
  assert.match(schema,/speaker_name_snapshot text not null/)
  assert.doesNotMatch(schema,/on delete cascade|roll_data|system_data|visibility/)
  assert.match(schema,/kind = 'character_message'/)
  assert.match(schema,/char_length\(body\) between 1 and 4000/)
  assert.match(schema,/round_messages_body_not_blank/)
})
test('SELECT is membership-only including locked GM exception; no admin/superadmin helper or policy bypass',()=>{
  assert.match(reader,/membership.user_id = \(select auth.uid\(\)\)/)
  assert.match(reader,/round.locked_at is null or membership.role = 'game_master'/)
  assert.doesNotMatch(reader,/can_view_round|is_admin|is_superadmin/)
  assert.match(reader,/on public.round_messages for select to authenticated/)
  assert.match(schema,/enable row level security/)
  assert.match(schema,/revoke all on table public.round_messages from public, anon, authenticated/)
  assert.match(reader,/grant select on table public.round_messages to authenticated/)
  assert.doesNotMatch(code,/grant\s+(?:insert|update|delete|all)\b|for\s+(?:insert|update|delete)\s+to/i)
})
test('send exposes only four inputs; user, role, current active character, owner, round, snapshot and ordering are server-derived',()=>{
  assert.match(sender,/p_round_id uuid,\s+p_body text,\s+p_client_request_id uuid,\s+p_expected_active_character_id uuid\s*\)/)
  assert.match(sender,/caller_user_id uuid := auth.uid\(\)/)
  assert.match(sender,/owner_user_id = caller_user_id and round_id = p_round_id\s+and deleted_at is null\s+for share/)
  assert.match(sender,/where round_id = p_round_id and user_id = caller_user_id for share/)
  assert.match(sender,/current_membership.active_character_id is distinct from p_expected_active_character_id/)
  assert.match(sender,/current_membership.active_character_id is null/)
  assert.match(sender,/speaker_name := current_character.name/)
  assert.match(sender,/speaker_kind := 'game_master';\s+speaker_name := 'Spielleitung'/)
  assert.match(sender,/case when speaker_kind = 'character' then current_character.id else null end/)
})
test('round/member/character locks protect authorization and archived/locked write guards precede INSERT',()=>{
  assert.match(sender,/from public.rounds where id = p_round_id for share/)
  for(const guard of ["current_round.locked_at is not null","current_round.status = 'archived'","current_membership.role = 'game_master'","current_membership.role = 'player'"]) {
    assert.ok(sender.indexOf(guard)>0)
    assert.ok(sender.indexOf(guard)<sender.indexOf('insert into public.round_messages'))
  }
  assert.doesNotMatch(sender,/status = 'paused'/)
  assert.ok(sender.indexOf('if not public.can_read_round_messages')<sender.indexOf('return message'))
})
test('idempotency and round sequences use separate transaction-scoped locks and unique database backstops',()=>{
  assert.match(schema,/unique \(round_id, round_seq\)/)
  assert.match(schema,/unique \(author_user_id, client_request_id\)/)
  assert.equal((sender.match(/pg_advisory_xact_lock/g)||[]).length,2)
  assert.match(sender,/'round-message-request:' \|\| caller_user_id::text \|\| ':' \|\| p_client_request_id::text/)
  assert.match(sender,/'round-message-sequence:' \|\| p_round_id::text/)
  assert.ok(sender.indexOf("'round-message-sequence:'")<sender.indexOf('max(round_seq)'))
  assert.match(sender,/where author_user_id = caller_user_id and client_request_id = p_client_request_id/)
  assert.match(sender,/message.round_id <> p_round_id or message.body <> p_body/)
  assert.match(sender,/coalesce\(max\(round_seq\), 0\) \+ 1/)
  assert.doesNotMatch(sender,/nextval|setval|create sequence/)
})
test('definers have empty search paths, qualified tables and explicit authenticated-only execute grants',()=>{
  assert.equal((code.match(/security definer\s+set search_path = ''/g)||[]).length,2)
  assert.doesNotMatch(code,/\b(?:from|join|into)\s+(?:rounds|characters|round_messages|round_memberships)\b/)
  assert.match(sender,/revoke all on function public.send_round_message\(uuid, text, uuid, uuid\) from public, anon/)
  assert.match(sender,/grant execute on function public.send_round_message\(uuid, text, uuid, uuid\) to authenticated/)
})
test('publication migration only adds round_messages with an existence guard and leaves other tables untouched',()=>{
  assert.match(publication,/if not exists[\s\S]*tablename = 'round_messages'/)
  assert.equal((publication.match(/alter publication/g)||[]).length,1)
  assert.match(publication,/alter publication supabase_realtime add table public.round_messages/)
  assert.doesNotMatch(publication,/\b(?:drop|create|set|delete|truncate)\b/i)
})
