import type { CharacterTemplateDefinition } from '../types'

export const vaesenTemplateV1: CharacterTemplateDefinition = {
  key: 'vaesen',
  name: 'Vaesen',
  version: 1,
  sections: [
    {
      key: 'section_basic_data',
      label: 'Grunddaten',
      order: 10,
      width: 'full',
      fields: [
        {
          key: 'name',
          label: 'Name',
          type: 'character_name',
          order: 10,
        },
        {
          key: 'age_group',
          label: 'Alter / Altersgruppe',
          type: 'short',
          order: 20,
        },
        {
          key: 'archetype',
          label: 'Archetyp',
          type: 'short',
          order: 30,
        },
        {
          key: 'motivation',
          label: 'Motivation',
          type: 'long',
          order: 40,
        },
        {
          key: 'trauma',
          label: 'Trauma',
          type: 'long',
          order: 50,
        },
        {
          key: 'dark_secret',
          label: 'Dunkles Geheimnis',
          type: 'long',
          order: 60,
        },
      ],
    },
    {
      key: 'section_relationships',
      label: 'Beziehungen',
      order: 20,
      width: 'full',
      fields: [
        {
          key: 'relationship_1',
          label: 'SC 1',
          type: 'short',
          order: 10,
        },
        {
          key: 'relationship_2',
          label: 'SC 2',
          type: 'short',
          order: 20,
        },
        {
          key: 'relationship_3',
          label: 'SC 3',
          type: 'short',
          order: 30,
        },
        {
          key: 'relationship_4',
          label: 'SC 4',
          type: 'short',
          order: 40,
        },
      ],
    },
    {
      key: 'section_attributes',
      label: 'Attribute',
      order: 30,
      width: 'half',
      fields: [
        {
          key: 'physique',
          label: 'Physis',
          type: 'short',
          order: 10,
        },
        {
          key: 'precision',
          label: 'Präzision',
          type: 'short',
          order: 20,
        },
        {
          key: 'logic',
          label: 'Logik',
          type: 'short',
          order: 30,
        },
        {
          key: 'empathy',
          label: 'Empathie',
          type: 'short',
          order: 40,
        },
      ],
    },
    {
      key: 'section_resources',
      label: 'Vermögen',
      order: 40,
      width: 'small',
      fields: [
        {
          key: 'resources',
          label: 'Vermögen',
          type: 'short',
          order: 10,
        },
      ],
    },
    {
      key: 'section_conditions',
      label: 'Zustände',
      order: 50,
      width: 'half',
      groups: [
        {
          key: 'group_physical_conditions',
          label: 'Körperlich',
          order: 10,
          fields: [
            {
              key: 'physical_exhausted',
              label: 'Erschöpft',
              type: 'check',
              order: 10,
            },
            {
              key: 'physical_battered',
              label: 'Angeschlagen',
              type: 'check',
              order: 20,
            },
            {
              key: 'physical_injured',
              label: 'Verletzt',
              type: 'check',
              order: 30,
            },
            {
              key: 'physical_broken',
              label: 'Gebrochen',
              type: 'check',
              order: 40,
            },
          ],
        },
        {
          key: 'group_mental_conditions',
          label: 'Geistig',
          order: 20,
          fields: [
            {
              key: 'mental_angry',
              label: 'Wütend',
              type: 'check',
              order: 10,
            },
            {
              key: 'mental_frightened',
              label: 'Verängstigt',
              type: 'check',
              order: 20,
            },
            {
              key: 'mental_hopeless',
              label: 'Hoffnungslos',
              type: 'check',
              order: 30,
            },
            {
              key: 'mental_broken',
              label: 'Gebrochen',
              type: 'check',
              order: 40,
            },
          ],
        },
      ],
    },
    {
      key: 'section_skills',
      label: 'Fertigkeiten',
      order: 60,
      width: 'full',
      fields: [
        {
          key: 'agility',
          label: 'Beweglichkeit (Physis)',
          type: 'short',
          order: 10,
        },
        {
          key: 'force',
          label: 'Kraft (Physis)',
          type: 'short',
          order: 20,
        },
        {
          key: 'close_combat',
          label: 'Nahkampf (Physis)',
          type: 'short',
          order: 30,
        },
        {
          key: 'ranged_combat',
          label: 'Fernkampf (Präzision)',
          type: 'short',
          order: 40,
        },
        {
          key: 'stealth',
          label: 'Heimlichkeit (Präzision)',
          type: 'short',
          order: 50,
        },
        {
          key: 'medicine',
          label: 'Medizin (Präzision)',
          type: 'short',
          order: 60,
        },
        {
          key: 'learning',
          label: 'Bildung (Logik)',
          type: 'short',
          order: 70,
        },
        {
          key: 'investigation',
          label: 'Ermittlung (Logik)',
          type: 'short',
          order: 80,
        },
        {
          key: 'vigilance',
          label: 'Wachsamkeit (Logik)',
          type: 'short',
          order: 90,
        },
        {
          key: 'observation',
          label: 'Beobachtung (Empathie)',
          type: 'short',
          order: 100,
        },
        {
          key: 'inspiration',
          label: 'Inspiration (Empathie)',
          type: 'short',
          order: 110,
        },
        {
          key: 'manipulation',
          label: 'Manipulation (Empathie)',
          type: 'short',
          order: 120,
        },
      ],
    },
    {
      key: 'section_talents',
      label: 'Talente',
      order: 70,
      width: 'half',
      fields: [
        {
          key: 'talents',
          label: 'Talente',
          type: 'long',
          order: 10,
        },
      ],
    },
    {
      key: 'section_insights_and_defects',
      label: 'Erkenntnisse & Gebrechen',
      order: 80,
      width: 'half',
      fields: [
        {
          key: 'insights_and_defects',
          label: 'Erkenntnisse & Gebrechen',
          type: 'long',
          order: 10,
        },
      ],
    },
    {
      key: 'section_advantages',
      label: 'Vorteile',
      order: 90,
      width: 'half',
      fields: [
        {
          key: 'advantages',
          label: 'Vorteile',
          type: 'long',
          order: 10,
        },
      ],
    },
    {
      key: 'section_equipment',
      label: 'Ausrüstung',
      order: 100,
      width: 'half',
      fields: [
        {
          key: 'equipment',
          label: 'Ausrüstung',
          type: 'long',
          order: 10,
        },
      ],
    },
    {
      key: 'section_armor',
      label: 'Rüstung',
      order: 110,
      width: 'half',
      fields: [
        {
          key: 'armor',
          label: 'Rüstung',
          type: 'short',
          order: 10,
        },
        {
          key: 'armor_protection',
          label: 'Schutz',
          type: 'short',
          order: 20,
        },
        {
          key: 'armor_agility',
          label: 'Beweglichkeit',
          type: 'short',
          order: 30,
        },
      ],
    },
    {
      key: 'section_weapons',
      label: 'Waffen',
      order: 120,
      width: 'half',
      fields: [
        {
          key: 'weapons',
          label: 'Waffen',
          type: 'long',
          order: 10,
        },
      ],
    },
    {
      key: 'section_memento',
      label: 'Memento',
      order: 130,
      width: 'half',
      fields: [
        {
          key: 'memento',
          label: 'Memento',
          type: 'long',
          order: 10,
        },
      ],
    },
    {
      key: 'section_experience',
      label: 'Erfahrung',
      order: 140,
      width: 'small',
      fields: [
        {
          key: 'experience_1',
          label: 'Erfahrung 1',
          type: 'check',
          order: 10,
          showLabel: false,
        },
        {
          key: 'experience_2',
          label: 'Erfahrung 2',
          type: 'check',
          order: 20,
          showLabel: false,
        },
        {
          key: 'experience_3',
          label: 'Erfahrung 3',
          type: 'check',
          order: 30,
          showLabel: false,
        },
        {
          key: 'experience_4',
          label: 'Erfahrung 4',
          type: 'check',
          order: 40,
          showLabel: false,
        },
        {
          key: 'experience_5',
          label: 'Erfahrung 5',
          type: 'check',
          order: 50,
          showLabel: false,
        },
        {
          key: 'experience_6',
          label: 'Erfahrung 6',
          type: 'check',
          order: 60,
          showLabel: false,
        },
        {
          key: 'experience_7',
          label: 'Erfahrung 7',
          type: 'check',
          order: 70,
          showLabel: false,
        },
        {
          key: 'experience_8',
          label: 'Erfahrung 8',
          type: 'check',
          order: 80,
          showLabel: false,
        },
        {
          key: 'experience_9',
          label: 'Erfahrung 9',
          type: 'check',
          order: 90,
          showLabel: false,
        },
        {
          key: 'experience_10',
          label: 'Erfahrung 10',
          type: 'check',
          order: 100,
          showLabel: false,
        },
      ],
    },
  ],
}
