-- Diese Migration bringt die Supabase-Struktur auf den Stand des aktuellen
-- Frontend-Codes. Sie ist absichtlich defensiv geschrieben:
-- - Tabellen werden bei Bedarf angelegt
-- - fehlende Spalten werden per ALTER TABLE ergänzt
-- - bestehende Daten sollen dabei erhalten bleiben

create extension if not exists pgcrypto;

create table if not exists public.coc_characters (
  id bigint generated by default as identity primary key,
  name text,
  played_by text,
  profession text,
  birthdate date,
  age integer,
  gender text,
  residence text,
  birthplace text,
  str integer default 50,
  dex integer default 50,
  con integer default 50,
  siz integer default 50,
  intell integer default 50,
  app integer default 50,
  pow integer default 50,
  edu integer default 50,
  mov integer default 8,
  hitpoints integer,
  sanity integer,
  luck integer,
  magic_points integer,
  custom_skill_name text,
  custom_skill_value integer,
  background text,
  important_people text,
  important_places text,
  dodge integer default 0,
  melee integer default 25,
  firearm_malfunction integer default 0,
  ranged_firearm integer default 20,
  rifle_shotgun integer default 25,
  accounting integer default 0,
  anthropology integer default 0,
  appraise integer default 0,
  archaeology integer default 0,
  charm integer default 0,
  climb integer default 0,
  credit_rating integer default 0,
  cthulhu_mythos integer default 0,
  disguise integer default 0,
  drive integer default 0,
  electrical_repair integer default 0,
  fast_talk integer default 0,
  fighting integer default 0,
  firearms integer default 0,
  first_aid integer default 0,
  history integer default 0,
  intimidate integer default 0,
  jump integer default 0,
  language_own integer default 0,
  language_other integer default 0,
  law integer default 0,
  library_use integer default 0,
  listen integer default 0,
  locksmith integer default 0,
  mechanical_repair integer default 0,
  medicine integer default 0,
  natural_world integer default 0,
  navigate integer default 0,
  occult integer default 0,
  operate_heavy_machinery integer default 0,
  persuade integer default 0,
  pilot integer default 0,
  psychology integer default 0,
  psychoanalysis integer default 0,
  ride integer default 0,
  science integer default 0,
  sleight_of_hand integer default 0,
  spot_hidden integer default 0,
  stealth integer default 0,
  survival integer default 0,
  swim integer default 0,
  throw integer default 0,
  track integer default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.coc_characters add column if not exists name text;
alter table public.coc_characters add column if not exists played_by text;
alter table public.coc_characters add column if not exists profession text;
alter table public.coc_characters add column if not exists birthdate date;
alter table public.coc_characters add column if not exists age integer;
alter table public.coc_characters add column if not exists gender text;
alter table public.coc_characters add column if not exists residence text;
alter table public.coc_characters add column if not exists birthplace text;
alter table public.coc_characters add column if not exists str integer default 50;
alter table public.coc_characters add column if not exists dex integer default 50;
alter table public.coc_characters add column if not exists con integer default 50;
alter table public.coc_characters add column if not exists siz integer default 50;
alter table public.coc_characters add column if not exists intell integer default 50;
alter table public.coc_characters add column if not exists app integer default 50;
alter table public.coc_characters add column if not exists pow integer default 50;
alter table public.coc_characters add column if not exists edu integer default 50;
alter table public.coc_characters add column if not exists mov integer default 8;
alter table public.coc_characters add column if not exists hitpoints integer;
alter table public.coc_characters add column if not exists sanity integer;
alter table public.coc_characters add column if not exists luck integer;
alter table public.coc_characters add column if not exists magic_points integer;
alter table public.coc_characters add column if not exists custom_skill_name text;
alter table public.coc_characters add column if not exists custom_skill_value integer;
alter table public.coc_characters add column if not exists background text;
alter table public.coc_characters add column if not exists important_people text;
alter table public.coc_characters add column if not exists important_places text;
alter table public.coc_characters add column if not exists dodge integer default 0;
alter table public.coc_characters add column if not exists melee integer default 25;
alter table public.coc_characters add column if not exists firearm_malfunction integer default 0;
alter table public.coc_characters add column if not exists ranged_firearm integer default 20;
alter table public.coc_characters add column if not exists rifle_shotgun integer default 25;
alter table public.coc_characters add column if not exists accounting integer default 0;
alter table public.coc_characters add column if not exists anthropology integer default 0;
alter table public.coc_characters add column if not exists appraise integer default 0;
alter table public.coc_characters add column if not exists archaeology integer default 0;
alter table public.coc_characters add column if not exists charm integer default 0;
alter table public.coc_characters add column if not exists climb integer default 0;
alter table public.coc_characters add column if not exists credit_rating integer default 0;
alter table public.coc_characters add column if not exists cthulhu_mythos integer default 0;
alter table public.coc_characters add column if not exists disguise integer default 0;
alter table public.coc_characters add column if not exists drive integer default 0;
alter table public.coc_characters add column if not exists electrical_repair integer default 0;
alter table public.coc_characters add column if not exists fast_talk integer default 0;
alter table public.coc_characters add column if not exists fighting integer default 0;
alter table public.coc_characters add column if not exists firearms integer default 0;
alter table public.coc_characters add column if not exists first_aid integer default 0;
alter table public.coc_characters add column if not exists history integer default 0;
alter table public.coc_characters add column if not exists intimidate integer default 0;
alter table public.coc_characters add column if not exists jump integer default 0;
alter table public.coc_characters add column if not exists language_own integer default 0;
alter table public.coc_characters add column if not exists language_other integer default 0;
alter table public.coc_characters add column if not exists law integer default 0;
alter table public.coc_characters add column if not exists library_use integer default 0;
alter table public.coc_characters add column if not exists listen integer default 0;
alter table public.coc_characters add column if not exists locksmith integer default 0;
alter table public.coc_characters add column if not exists mechanical_repair integer default 0;
alter table public.coc_characters add column if not exists medicine integer default 0;
alter table public.coc_characters add column if not exists natural_world integer default 0;
alter table public.coc_characters add column if not exists navigate integer default 0;
alter table public.coc_characters add column if not exists occult integer default 0;
alter table public.coc_characters add column if not exists operate_heavy_machinery integer default 0;
alter table public.coc_characters add column if not exists persuade integer default 0;
alter table public.coc_characters add column if not exists pilot integer default 0;
alter table public.coc_characters add column if not exists psychology integer default 0;
alter table public.coc_characters add column if not exists psychoanalysis integer default 0;
alter table public.coc_characters add column if not exists ride integer default 0;
alter table public.coc_characters add column if not exists science integer default 0;
alter table public.coc_characters add column if not exists sleight_of_hand integer default 0;
alter table public.coc_characters add column if not exists spot_hidden integer default 0;
alter table public.coc_characters add column if not exists stealth integer default 0;
alter table public.coc_characters add column if not exists survival integer default 0;
alter table public.coc_characters add column if not exists swim integer default 0;
alter table public.coc_characters add column if not exists throw integer default 0;
alter table public.coc_characters add column if not exists track integer default 0;
alter table public.coc_characters add column if not exists created_at timestamptz not null default now();
alter table public.coc_characters add column if not exists updated_at timestamptz not null default now();

create table if not exists public.splinter_portals_characters (
  id bigint generated by default as identity primary key,
  name text,
  klasse text,
  level integer default 1,
  health integer default 10,
  mana integer default 10,
  strength integer default 50,
  agility integer default 50,
  intelligence integer default 50,
  charisma integer default 50,
  skills text default '[]',
  items text default '[]',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.splinter_portals_characters add column if not exists name text;
alter table public.splinter_portals_characters add column if not exists klasse text;
alter table public.splinter_portals_characters add column if not exists level integer default 1;
alter table public.splinter_portals_characters add column if not exists health integer default 10;
alter table public.splinter_portals_characters add column if not exists mana integer default 10;
alter table public.splinter_portals_characters add column if not exists strength integer default 50;
alter table public.splinter_portals_characters add column if not exists agility integer default 50;
alter table public.splinter_portals_characters add column if not exists intelligence integer default 50;
alter table public.splinter_portals_characters add column if not exists charisma integer default 50;
alter table public.splinter_portals_characters add column if not exists skills text default '[]';
alter table public.splinter_portals_characters add column if not exists items text default '[]';
alter table public.splinter_portals_characters add column if not exists created_at timestamptz not null default now();
alter table public.splinter_portals_characters add column if not exists updated_at timestamptz not null default now();

create table if not exists public.characters (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  system text not null,
  data jsonb not null default '{}'::jsonb,
  owner_user_id uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.characters add column if not exists owner_user_id uuid references auth.users (id) on delete set null;
alter table public.characters add column if not exists created_at timestamptz not null default now();
alter table public.characters add column if not exists updated_at timestamptz not null default now();

create table if not exists public.session_players (
  id uuid primary key default gen_random_uuid(),
  session_id text not null,
  user_id uuid not null references auth.users (id) on delete cascade,
  display_name text,
  role text not null default 'player' check (role in ('gm', 'player')),
  character_id uuid references public.characters (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (session_id, user_id)
);

alter table public.session_players add column if not exists role text not null default 'player';
alter table public.session_players add column if not exists display_name text;
alter table public.session_players add column if not exists character_id uuid references public.characters (id) on delete set null;
alter table public.session_players add column if not exists created_at timestamptz not null default now();
alter table public.session_players add column if not exists updated_at timestamptz not null default now();

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists trg_coc_characters_updated_at on public.coc_characters;
create trigger trg_coc_characters_updated_at
before update on public.coc_characters
for each row
execute function public.set_updated_at();

drop trigger if exists trg_splinter_portals_characters_updated_at on public.splinter_portals_characters;
create trigger trg_splinter_portals_characters_updated_at
before update on public.splinter_portals_characters
for each row
execute function public.set_updated_at();

drop trigger if exists trg_characters_updated_at on public.characters;
create trigger trg_characters_updated_at
before update on public.characters
for each row
execute function public.set_updated_at();

drop trigger if exists trg_session_players_updated_at on public.session_players;
create trigger trg_session_players_updated_at
before update on public.session_players
for each row
execute function public.set_updated_at();

alter table public.coc_characters enable row level security;
alter table public.splinter_portals_characters enable row level security;
alter table public.characters enable row level security;
alter table public.session_players enable row level security;

drop policy if exists "coc_characters_select_authenticated" on public.coc_characters;
create policy "coc_characters_select_authenticated"
on public.coc_characters
for select
to authenticated
using (true);

drop policy if exists "coc_characters_insert_authenticated" on public.coc_characters;
create policy "coc_characters_insert_authenticated"
on public.coc_characters
for insert
to authenticated
with check (true);

drop policy if exists "coc_characters_update_authenticated" on public.coc_characters;
create policy "coc_characters_update_authenticated"
on public.coc_characters
for update
to authenticated
using (true)
with check (true);

drop policy if exists "coc_characters_delete_authenticated" on public.coc_characters;
create policy "coc_characters_delete_authenticated"
on public.coc_characters
for delete
to authenticated
using (true);

drop policy if exists "splinter_characters_select_authenticated" on public.splinter_portals_characters;
create policy "splinter_characters_select_authenticated"
on public.splinter_portals_characters
for select
to authenticated
using (true);

drop policy if exists "splinter_characters_insert_authenticated" on public.splinter_portals_characters;
create policy "splinter_characters_insert_authenticated"
on public.splinter_portals_characters
for insert
to authenticated
with check (true);

drop policy if exists "splinter_characters_update_authenticated" on public.splinter_portals_characters;
create policy "splinter_characters_update_authenticated"
on public.splinter_portals_characters
for update
to authenticated
using (true)
with check (true);

drop policy if exists "splinter_characters_delete_authenticated" on public.splinter_portals_characters;
create policy "splinter_characters_delete_authenticated"
on public.splinter_portals_characters
for delete
to authenticated
using (true);

drop policy if exists "characters_select_authenticated" on public.characters;
create policy "characters_select_authenticated"
on public.characters
for select
to authenticated
using (true);

drop policy if exists "characters_insert_authenticated" on public.characters;
create policy "characters_insert_authenticated"
on public.characters
for insert
to authenticated
with check (auth.uid() = owner_user_id or owner_user_id is null);

drop policy if exists "characters_update_authenticated" on public.characters;
create policy "characters_update_authenticated"
on public.characters
for update
to authenticated
using (auth.uid() = owner_user_id or owner_user_id is null)
with check (auth.uid() = owner_user_id or owner_user_id is null);

drop policy if exists "characters_delete_authenticated" on public.characters;
create policy "characters_delete_authenticated"
on public.characters
for delete
to authenticated
using (auth.uid() = owner_user_id or owner_user_id is null);

drop policy if exists "session_players_select_authenticated" on public.session_players;
create policy "session_players_select_authenticated"
on public.session_players
for select
to authenticated
using (true);

drop policy if exists "session_players_insert_authenticated" on public.session_players;
create policy "session_players_insert_authenticated"
on public.session_players
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "session_players_update_authenticated" on public.session_players;
create policy "session_players_update_authenticated"
on public.session_players
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "session_players_delete_authenticated" on public.session_players;
create policy "session_players_delete_authenticated"
on public.session_players
for delete
to authenticated
using (auth.uid() = user_id);

create table if not exists public.sessions (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text,
  description text,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.sessions add column if not exists slug text;
alter table public.sessions add column if not exists title text;
alter table public.sessions add column if not exists description text;
alter table public.sessions add column if not exists created_by uuid references auth.users (id) on delete set null;
alter table public.sessions add column if not exists created_at timestamptz not null default now();
alter table public.sessions add column if not exists updated_at timestamptz not null default now();

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'sessions_slug_key'
  ) then
    alter table public.sessions
    add constraint sessions_slug_key unique (slug);
  end if;
end
$$;

update public.sessions
set slug = coalesce(nullif(slug, ''), id::text)
where slug is null or slug = '';

alter table public.sessions
alter column slug set not null;

create table if not exists public.notebook_pages (
  session_slug text not null references public.sessions (slug) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  title text,
  content text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (session_slug, user_id)
);

create table if not exists public.whiteboard_images (
  id text primary key,
  session_slug text not null references public.sessions (slug) on delete cascade,
  src text not null,
  x double precision not null default 0,
  y double precision not null default 0,
  width double precision not null default 320,
  height double precision not null default 240,
  revealed boolean not null default false,
  name text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.whiteboard_notes (
  id text primary key,
  session_slug text not null references public.sessions (slug) on delete cascade,
  author_id uuid references auth.users (id) on delete set null,
  text text not null,
  x double precision not null default 0,
  y double precision not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.whiteboard_tokens (
  session_slug text not null references public.sessions (slug) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  x double precision not null default 0,
  y double precision not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (session_slug, user_id)
);

drop trigger if exists trg_sessions_updated_at on public.sessions;
create trigger trg_sessions_updated_at
before update on public.sessions
for each row
execute function public.set_updated_at();

drop trigger if exists trg_notebook_pages_updated_at on public.notebook_pages;
create trigger trg_notebook_pages_updated_at
before update on public.notebook_pages
for each row
execute function public.set_updated_at();

drop trigger if exists trg_whiteboard_images_updated_at on public.whiteboard_images;
create trigger trg_whiteboard_images_updated_at
before update on public.whiteboard_images
for each row
execute function public.set_updated_at();

drop trigger if exists trg_whiteboard_notes_updated_at on public.whiteboard_notes;
create trigger trg_whiteboard_notes_updated_at
before update on public.whiteboard_notes
for each row
execute function public.set_updated_at();

drop trigger if exists trg_whiteboard_tokens_updated_at on public.whiteboard_tokens;
create trigger trg_whiteboard_tokens_updated_at
before update on public.whiteboard_tokens
for each row
execute function public.set_updated_at();

alter table public.sessions enable row level security;
alter table public.notebook_pages enable row level security;
alter table public.whiteboard_images enable row level security;
alter table public.whiteboard_notes enable row level security;
alter table public.whiteboard_tokens enable row level security;

drop policy if exists "sessions_select_authenticated" on public.sessions;
create policy "sessions_select_authenticated"
on public.sessions
for select
to anon, authenticated
using (true);

drop policy if exists "sessions_insert_authenticated" on public.sessions;
create policy "sessions_insert_authenticated"
on public.sessions
for insert
to anon, authenticated
with check (auth.uid() = created_by or created_by is null);

drop policy if exists "sessions_update_authenticated" on public.sessions;
create policy "sessions_update_authenticated"
on public.sessions
for update
to anon, authenticated
using (true)
with check (true);

drop policy if exists "notebook_pages_select_authenticated" on public.notebook_pages;
create policy "notebook_pages_select_authenticated"
on public.notebook_pages
for select
to authenticated
using (true);

drop policy if exists "notebook_pages_insert_authenticated" on public.notebook_pages;
create policy "notebook_pages_insert_authenticated"
on public.notebook_pages
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "notebook_pages_update_authenticated" on public.notebook_pages;
create policy "notebook_pages_update_authenticated"
on public.notebook_pages
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "whiteboard_images_select_authenticated" on public.whiteboard_images;
create policy "whiteboard_images_select_authenticated"
on public.whiteboard_images
for select
to authenticated
using (true);

drop policy if exists "whiteboard_images_insert_authenticated" on public.whiteboard_images;
create policy "whiteboard_images_insert_authenticated"
on public.whiteboard_images
for insert
to authenticated
with check (true);

drop policy if exists "whiteboard_images_update_authenticated" on public.whiteboard_images;
create policy "whiteboard_images_update_authenticated"
on public.whiteboard_images
for update
to authenticated
using (true)
with check (true);

drop policy if exists "whiteboard_notes_select_authenticated" on public.whiteboard_notes;
create policy "whiteboard_notes_select_authenticated"
on public.whiteboard_notes
for select
to authenticated
using (true);

drop policy if exists "whiteboard_notes_insert_authenticated" on public.whiteboard_notes;
create policy "whiteboard_notes_insert_authenticated"
on public.whiteboard_notes
for insert
to authenticated
with check (auth.uid() = author_id or author_id is null);

drop policy if exists "whiteboard_notes_update_authenticated" on public.whiteboard_notes;
create policy "whiteboard_notes_update_authenticated"
on public.whiteboard_notes
for update
to authenticated
using (true)
with check (true);

drop policy if exists "whiteboard_tokens_select_authenticated" on public.whiteboard_tokens;
create policy "whiteboard_tokens_select_authenticated"
on public.whiteboard_tokens
for select
to authenticated
using (true);

drop policy if exists "whiteboard_tokens_insert_authenticated" on public.whiteboard_tokens;
create policy "whiteboard_tokens_insert_authenticated"
on public.whiteboard_tokens
for insert
to authenticated
with check (auth.uid() = user_id);

drop policy if exists "whiteboard_tokens_update_authenticated" on public.whiteboard_tokens;
create policy "whiteboard_tokens_update_authenticated"
on public.whiteboard_tokens
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);


create table if not exists public.app_admins (
  user_id uuid primary key references auth.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.app_admins enable row level security;

drop policy if exists "app_admins_select_authenticated" on public.app_admins;
create policy "app_admins_select_authenticated"
on public.app_admins
for select
to authenticated
using (auth.uid() = user_id);

create or replace function public.is_app_admin(check_user_id uuid)
returns boolean
language sql
stable
as $$
  select exists (
    select 1
    from public.app_admins admins
    where admins.user_id = check_user_id
  );
$$;

drop policy if exists "sessions_delete_owner_or_admin" on public.sessions;
create policy "sessions_delete_owner_or_admin"
on public.sessions
for delete
to authenticated
using (
  auth.uid() = created_by
  or public.is_app_admin(auth.uid())
);

drop policy if exists "session_players_update_self_or_admin" on public.session_players;
create policy "session_players_update_self_or_admin"
on public.session_players
for update
to authenticated
using (
  auth.uid() = user_id
  or public.is_app_admin(auth.uid())
)
with check (
  auth.uid() = user_id
  or public.is_app_admin(auth.uid())
);

drop policy if exists "session_players_delete_self_or_admin" on public.session_players;
create policy "session_players_delete_self_or_admin"
on public.session_players
for delete
to authenticated
using (
  auth.uid() = user_id
  or public.is_app_admin(auth.uid())
);
